print("My Father Name is Chellam(a)ravi")
print("My Mother Name is Laxmi")
print("My Sisters Name is Pavi&Rathanam")
print("My Brother Name is Muthu Nayagam")
print("My friends Name is Nagalingam&Predeep")
